import { Inter } from "next/font/google";
import { MantineProvider } from '@mantine/core';
import { ToastContainer } from "react-toastify";
import "./globals.css";
import '@mantine/core/styles.css';
import 'react-toastify/dist/ReactToastify.css';
import '@mantine/dates/styles.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "TaskTrek",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <div className='bg-colorGradient'></div>
        <MantineProvider>
          <main className="app">
            {children}
          </main>
          <ToastContainer />
        </MantineProvider>
      </body>
    </html>
  );
}
